# Generated by Django 4.2.1 on 2023-05-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0003_user_bio_user_name_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
